### ISSUE TITLE
[Bug] 在Replay中，信息显示异常

### ISSUE THREAD

**Issue by cxzlw** [AstralLing/generals.io-Helper#10]
![image](https://user-images.githubusercontent.com/55052188/166291166-752ac286-e29c-46ad-b602-278ed76d2510.png)
原因：Replay界面加入了POV栏，导致程序覆盖的位置出现了偏差
如果能在Replay中正常的显示数据，那对程序的测试和修改会更加的容易

**Comment by cxzlw** [comment]
好像有点难改，要改的有点多emmm
我试试想想有没有办法不改大多数代码，玩点骚操作（doge）

**Comment by AstralLing** [comment]
也许可以把 POV 这一列移到后面去（误

之前没注意过这个问题诶……实在不行的话把列编号改成倒过来取也好……就是工作量确实有点大emm

话说都是不睡觉人嘛（

**Comment by AstralLing** [comment]
似乎没完全修好，回放中队伍一行的 POV 选框会消失掉，怪

**Comment by cxzlw** [comment]
> 也许可以把 POV 这一列移到后面去（误
> 
> 之前没注意过这个问题诶……实在不行的话把列编号改成倒过来取也好……就是工作量确实有点大emm
> 
> 话说都是不睡觉人嘛（

嘻嘻我现在也没睡
